/*
 * MainFrame.java
 *
 * Created on February 28, 2008, 8:52 PM
 */

package naviswirelesscdc;

/**
 *
 * @author  dr. xinyu liu
 */
public class MainFrame extends java.awt.Frame {
    
    private NavisMain main;
    
    /** Creates new form MainFrame */
    public MainFrame(NavisMain main) {
        this.main = main;
        initComponents();
        
//        setMaximumSize(new java.awt.Dimension(240, 300));
//        setMinimumSize(new java.awt.Dimension(240, 300));
//        setPreferredSize(new java.awt.Dimension(240, 300));

        this.setLocation(0,0);
        this.setSize(240, 300);

//        this.setResizable(false);
        setLayout(new java.awt.BorderLayout());
    }

    public NavisMain getMain() {
        return main;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(java.awt.Color.white);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 203, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 197, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
