
package us.naviscorp.soa.wsdl.clientservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import us.naviscorp.soa.wsdl.clientservices.ClientServices;
import us.naviscorp.soa.wsdl.clientservices.ClientServices_Service;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ClientServices", targetNamespace = "http://www.naviscorp.us/soa/wsdl/clientservices", wsdlLocation = "http://localhost:8080/clientservices/clientservices?wsdl")
public class ClientServices_Service
    extends Service
{

    private final static URL WSDL_LOCATION;
    private final static QName CLIENTSERVICES = new QName("http://www.naviscorp.us/soa/wsdl/clientservices", "ClientServices");
    private final static QName CLIENTSERVICESPORT = new QName("http://www.naviscorp.us/soa/wsdl/clientservices", "ClientServicesPort");

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/clientservices/clientservices?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ClientServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientServices_Service() {
        super(WSDL_LOCATION, CLIENTSERVICES);
    }

    /**
     * 
     * @return
     *     returns ClientServices
     */
    @WebEndpoint(name = "ClientServicesPort")
    public ClientServices getClientServicesPort() {
        return (ClientServices)super.getPort(CLIENTSERVICESPORT, ClientServices.class);
    }

}
