
package us.naviscorp.soa.wsdl.clientservices;

import javax.xml.ws.WebFault;
import us.naviscorp.soa.wsdl.clientservices.UploadException;
import us.naviscorp.soa.wsdl.clientservices.UploadException_Exception;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "UploadException", targetNamespace = "http://www.naviscorp.us/soa/wsdl/clientservices")
public class UploadException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UploadException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UploadException_Exception(String message, UploadException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public UploadException_Exception(String message, UploadException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: us.naviscorp.soa.wsdl.clientservices.UploadException
     */
    public UploadException getFaultInfo() {
        return faultInfo;
    }

}
